//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class arizaTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arizaTablosu()
        {
            this.onarimTablosu = new HashSet<onarimTablosu>();
        }
    
        public int arizaId { get; set; }
        public int modelFkId { get; set; }
        public int musteriFkId { get; set; }
        public string arizaNedeni { get; set; }
        public System.DateTime arizaGelisTar { get; set; }
    
        public virtual modelTablosu modelTablosu { get; set; }
        public virtual musteriTablosu musteriTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<onarimTablosu> onarimTablosu { get; set; }
    }
}
