//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeknikServisEntities : DbContext
    {
        public TeknikServisEntities()
            : base("name=TeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arizaTablosu> arizaTablosu { get; set; }
        public virtual DbSet<markaTablosu> markaTablosu { get; set; }
        public virtual DbSet<modelTablosu> modelTablosu { get; set; }
        public virtual DbSet<musteriTablosu> musteriTablosu { get; set; }
        public virtual DbSet<onarimTablosu> onarimTablosu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<urunTuruTablosu> urunTuruTablosu { get; set; }
    }
}
