//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modelTablosu()
        {
            this.arizaTablosu = new HashSet<arizaTablosu>();
        }
    
        public int modelId { get; set; }
        public int urunTuruFkId { get; set; }
        public int markaFkId { get; set; }
        public string modelSeri { get; set; }
        public string modelAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arizaTablosu> arizaTablosu { get; set; }
        public virtual markaTablosu markaTablosu { get; set; }
        public virtual urunTuruTablosu urunTuruTablosu { get; set; }
    }
}
