//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class onarimTablosu
    {
        public int onarimId { get; set; }
        public int arizaFkId { get; set; }
        public string onarimNedeni { get; set; }
        public System.DateTime onarimTeshisTar { get; set; }
        public System.DateTime onarimTar { get; set; }
        public string onarimUcret { get; set; }
    
        public virtual arizaTablosu arizaTablosu { get; set; }
    }
}
